version: 2.1
orbs:
  # orbs contain basic recipes and reproducible actions (install node, aws, etc.)
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
  # different jobs are called later in the workflows sections
jobs:
  build:
    docker:
      # the base image can run most needed actions with orbs
      # - image: cimg/base:stable
      - image: "cimg/node:16.13"
    steps:
      # install node and checkout code
      - node/install:
          node-version: "16.13"
      - checkout
      - aws-cli/setup
      - eb/setup
      # Use root level package.json to install dependencies in the frontend app
      - run:
          name: Installing BackEnd Dependencies
          command: |
            'npm run backend:install'
      - run:
          name: Install Front-End Dependencies
          command: |
            'npm run frontend:install'
      - run:
          name: Building Back-End
          command: |
            'npm run backend:build'
      - run:
          name: Building Front-End
          command: |
            'npm run frontend:build'
      - run:
          name: Deploying Front-End
          command: |
            'npm run frontend:deploy'
      - run:
          name: Deploying Back-End
          command: |
            'npm run backend:deploy'
workflows:
  udagram:
    jobs:
      - build
      - hold:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
      - deploy:
          requires:
            - hold
