version: 2.1
orbs:
  node: circleci/node@5.0.3
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@3.1.1
jobs:
  build:
    docker:
      - image: "cimg/node:14.15"
    steps:
      - node/install:
          node-version: "14.15"
      - checkout
      - aws-cli/setup
      - eb/setup
      - run:
          name: Installing Front-End Dependencies
          command: |
            npm run frontend:install
      - run:
          name: Installing Back-End Dependencies
          command: |
            npm run backend:install
      - run:
          name: Building Front-End
          command: |
            npm run frontend:build
      - run:
          name: Building Back-End
          command: |
            npm run backend:build
      - run:
          name: Deploying Front-End
          command: |
            npm run frontend:deploy
      - run:
          name: Deploying Back-End
          command: |
            npm run backend:deploy

workflows:
  udagram:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
